### ISSUE TITLE
Feature request: zapamiętaj dla użytkownika czego słuchał

### ISSUE THREAD

**Issue by pensjonatus** [techwriterkoduje/podcast-site#27]
Jako użytkownik, chciałbym kontynuować słuchanie podcastu.

- Dodać zapis do local storage
- Przy powracającym użytkowniku, wyświetlić: "kontynuuj słuchanie"
- Dodać opcję usunięcia zapisanego stanu
- [BONUS]: Użyć tego, żeby rozwiązać problem z grającym odcinkiem przy przejściu na inną stronę. Odcinek może grać dalej, ale potrzebujemy unoszący się w powietrzu player, który pozwala zatrzymać itp.

**Comment by piotrbartnik** [comment]
Działa świetnie po mergu https://github.com/techwriterkoduje/podcast-site/pull/28/files. Można zamknąć.

**Comment by pensjonatus** [comment]
Dzięki, Piotr. Nie zaimplementowałem wszystkich ficzerów, które tu opisałem, ale skoro jesteś zadowolony, to zamykam.
